[package]
name = "kcl-zed-extension"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/kcl.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.4.0"
